#ifndef BASICEXPORTER_GLOBAL_H
#define BASICEXPORTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASICEXPORTER_LIBRARY)
#  define BASICEXPORTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BASICEXPORTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BASICEXPORTER_GLOBAL_H
